### ISSUE TITLE
Is this plugin completely for Fluentd v0.x ?

### ISSUE THREAD

**Issue by daipom** [fluent/fluent-plugin-multiprocess#17]
Is this plugin completely for Fluentd v0.x ?

Fluentd v1.x has [the Multi Process Workers function](https://docs.fluentd.org/deployment/multi-process-workers).

If this plugin is completely for v0.x, then I will make a PR to add the info to README.

**Comment by tagomoris** [comment]
Basically, this plugin is for Fluentd v0.x (< 1.0). But, there is still a use case for this plugin with Fluentd v1.x.
If you want to run 2 or more Fluentd processes but any of configured plugins do not support the Multi-Process Workers, you may want to run Fluentd by this plugin (with special care of the configuration to avoid race).

**Comment by daipom** [comment]
@tagomoris Thanks so much! I understand!

Then I will make a PR to add that info to the README.
